{% set name = "tradingeconomics" %}
{% set version = "0.2.979" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ef9f26081c58be4ee5722a4b776f4a62653fb07bf02c52ef58618c7f56c18eca

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pandas
    - pip
    - python
    - websocket-client
  run:
    - pandas
    - python
    - websocket-client

test:
  imports:
    - tradingeconomics

about:
  home: "https://github.com/ieconomics/open-api"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Library to download data from Trading Economics API"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
